version: "3.8"

services:
  backend:
    stdin_open: true
    tty: true
    build: ./backend
    command: bash run_server.sh
    volumes:
      - ./backend/src/:/app/
    ports:
      - 5000:5000

  frontend:
    stdin_open: true
    tty: true
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
    ports:
      - 3000:3000